org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1
mod_id=mbelt
mod_name=MBelt
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=MVlate
mod_authors=MVlate
mod_description=MBelt is a mod that add a belt with basics utilities like quick access, little bags and extras slots that allow you to carry bundles and specials items on curios from other mods
curios_version=5.14.1+1.20.1

